version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cvhodit3nkoz"
s3_prefix = "hello-world"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides ="SubnetId=\"subnet-0eba31ec4ee63df53\" Name=\"hello-world\" EnvironmentType=\"test\" Owner=\"Platform\" ImageRecipeVersion=\"1.0.0\" ParentImage=\"/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2\""
image_repositories = []
